drop table if exists FILMS, GENRES, LIKES, MPA, USERS, FRIENDS;

create table FILMS (
    ID integer generated by default as identity primary key,
    NAME varchar(255),
    DESCRIPTION varchar(400),
    RELEASE_DATE date,
    DURATION integer
);

create table GENRES (
    ID integer primary key,
    NAME varchar(255) not null unique
);

create table MPA (
    ID integer primary key,
    NAME varchar(255) not null unique
);

create table USERS (
    ID integer generated by default as identity primary key,
    EMAIL varchar(255) not null,
    LOGIN varchar(255) not null,
    NAME varchar(255),
    BIRTHDAY date
);

create table LIKES (
    FILM_ID integer not null references FILMS (ID),
    USER_ID integer not null references USERS (ID),
    unique (FILM_ID, USER_ID)
);

create table FRIENDS (
    USER_ID integer not null references USERS,
    FRIEND_ID integer not null references USERS,
    unique (USER_ID, FRIEND_ID)
);
